# -*- coding: utf-8 -*-
"""Criação de um Modelo Preditivo para um E-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RrMB6wiQiXwORwtFr8r_ASClmRuN_tlm
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

dados = {
    'idade': [25, 34, 45, 23, 52, 36, 29, 41, 33, 48],
    'tempo_cadastro': [2, 5, 7, 1, 10, 4, 3, 6, 2, 8],
    'email_aberto': [1, 0, 1, 1, 0, 1, 1, 0, 1, 0],
    'clicou_link': [0, 0, 1, 1, 0, 1, 0, 1, 1, 0],
    'comprou': [0, 0, 1, 1, 0, 1, 0, 1, 1, 0]
}

df = pd.DataFrame(dados)

X = df[['idade', 'tempo_cadastro', 'email_aberto', 'clicou_link']]
y = df['comprou']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

modelo = DecisionTreeClassifier(random_state=42)
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)

print("Acurácia:", accuracy_score(y_test, y_pred))
print("Relatório de Classificação:\n", classification_report(y_test, y_pred))

plt.figure(figsize=(12,8))
plot_tree(modelo, feature_names=X.columns, class_names=['Não Comprou','Comprou'], filled=True)
plt.show()